spring:
  profiles:
    active: develop

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8090

---
spring.config.activate.on-profile: develop
stripe:
  simulator:
    base-uri: ${STRIPE_SIMULATOR_BASE_URI}

---
spring.config.activate.on-profile: test
stripe:
  simulator:
    base-uri: http://localhost:9999
